#!/usr/bin/env python3
"""
Generated by scripts/scrape_pokemon.py

Scrapes Pokemon data from PokéAPI and Bulbapedia to generate:
  - ../frontend/src/data/pokemon.ts  (TypeScript constants)
  - ../data/pokemon.json             (JSON for backend scoring)

Usage:
    python scripts/scrape_pokemon.py [--limit 1025] [--resume] [--no-bulbapedia]

Features:
  - Fetches all 1025 Pokemon from PokéAPI (pagination)
  - Per Pokemon: English name, types, generation, category, evolution chain, sprite URL
  - Chinese names from Bulbapedia HTML parsing
  - Pinyin + IPA derived from Chinese name using pypinyin
  - Resumable: skips already-fetched Pokemon (uses cache in data/cache/)
  - Rate limited: 100ms between requests
  - Best-effort: logs failures and uses placeholder data
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import httpx
from bs4 import BeautifulSoup

# Add backend root to sys.path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

try:
    from pypinyin import pinyin, Style, lazy_pinyin
    HAS_PYPINYIN = True
except ImportError:
    HAS_PYPINYIN = False
    print("[scrape] WARNING: pypinyin not installed. Pinyin will use placeholders.")

try:
    from dragonmapper import transcriptions
    HAS_DRAGONMAPPER = True
except ImportError:
    HAS_DRAGONMAPPER = False
    print("[scrape] WARNING: dragonmapper not installed. IPA will use placeholders.")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
_SCRIPT_DIR = Path(__file__).resolve().parent
_BACKEND_DIR = _SCRIPT_DIR.parent
_FRONTEND_DIR = _BACKEND_DIR.parent / "frontend"
_DATA_DIR = _BACKEND_DIR / "data"
_CACHE_DIR = _DATA_DIR / "cache"

_OUTPUT_JSON = _DATA_DIR / "pokemon.json"
_OUTPUT_TS = _FRONTEND_DIR / "src" / "data" / "pokemon.ts"

# Rate limiting
REQUEST_DELAY = 0.1  # 100ms between requests

POKEAPI_BASE = "https://pokeapi.co/api/v2"
BULBAPEDIA_BASE = "https://bulbapedia.bulbagarden.net/wiki"

GENERATION_MAP = {
    "generation-i": 1,
    "generation-ii": 2,
    "generation-iii": 3,
    "generation-iv": 4,
    "generation-v": 5,
    "generation-vi": 6,
    "generation-vii": 7,
    "generation-viii": 8,
    "generation-ix": 9,
}

TYPE_NAMES = {
    "normal", "fire", "water", "electric", "grass", "ice",
    "fighting", "poison", "ground", "flying", "psychic", "bug",
    "rock", "ghost", "dragon", "dark", "steel", "fairy",
}


# --------------------------------------------------------------------------- #
# Pinyin / IPA helpers
# --------------------------------------------------------------------------- #

def get_pinyin_tones(chinese: str) -> str:
    """Return pinyin with tone marks, e.g. 'Pēn Huǒ Lóng'."""
    if not chinese or not HAS_PYPINYIN:
        return ""
    try:
        result = pinyin(chinese, style=Style.TONE)
        return " ".join(item[0].capitalize() if i == 0 else item[0] for i, item in enumerate(result))
    except Exception:
        return ""


def get_pinyin_numbered(chinese: str) -> str:
    """Return pinyin with numbered tones, e.g. 'Pen1 Huo3 Long2'."""
    if not chinese or not HAS_PYPINYIN:
        return ""
    try:
        result = pinyin(chinese, style=Style.TONE3)
        return " ".join(item[0].capitalize() if i == 0 else item[0] for i, item in enumerate(result))
    except Exception:
        return ""


def get_ipa(pinyin_str: str) -> str:
    """Convert numbered pinyin to IPA using dragonmapper."""
    if not pinyin_str or not HAS_DRAGONMAPPER:
        return ""
    try:
        # dragonmapper expects numbered pinyin without spaces between syllables
        # Process syllable by syllable
        syllables = pinyin_str.split()
        ipa_parts = []
        for syl in syllables:
            try:
                ipa = transcriptions.pinyin_to_ipa(syl)
                ipa_parts.append(ipa)
            except Exception:
                ipa_parts.append(syl)
        return "/" + " ".join(ipa_parts) + "/"
    except Exception:
        return ""


def get_etymology(chinese: str) -> List[Dict[str, str]]:
    """Build etymology breakdown for each character."""
    if not chinese or not HAS_PYPINYIN:
        return []
    entries = []
    for char in chinese:
        if not char.strip():
            continue
        try:
            char_pinyin = pinyin(char, style=Style.TONE)[0][0]
        except Exception:
            char_pinyin = ""
        entries.append({
            "character": char,
            "pinyin": char_pinyin,
            "meaning": "",  # Meaning requires a dictionary lookup; left blank for scraper
        })
    return entries


# --------------------------------------------------------------------------- #
# PokéAPI fetching
# --------------------------------------------------------------------------- #

async def fetch_json(client: httpx.AsyncClient, url: str, cache_path: Optional[Path] = None) -> Optional[Dict]:
    """Fetch JSON from URL, using file cache if provided."""
    if cache_path and cache_path.exists():
        with open(cache_path, "r", encoding="utf-8") as f:
            return json.load(f)

    try:
        await asyncio.sleep(REQUEST_DELAY)
        resp = await client.get(url, timeout=15.0)
        resp.raise_for_status()
        data = resp.json()
        if cache_path:
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            with open(cache_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False)
        return data
    except Exception as e:
        log.warning(f"Failed to fetch {url}: {e}")
        return None


async def get_all_pokemon_list(client: httpx.AsyncClient, limit: int = 1025) -> List[Dict]:
    """Fetch paginated list of all Pokemon from PokéAPI."""
    url = f"{POKEAPI_BASE}/pokemon?limit={limit}&offset=0"
    data = await fetch_json(client, url, _CACHE_DIR / "pokemon_list.json")
    if data is None:
        return []
    return data.get("results", [])


async def get_pokemon_data(client: httpx.AsyncClient, name_or_id: str) -> Optional[Dict]:
    cache = _CACHE_DIR / "pokemon" / f"{name_or_id}.json"
    url = f"{POKEAPI_BASE}/pokemon/{name_or_id}"
    return await fetch_json(client, url, cache)


async def get_pokemon_species(client: httpx.AsyncClient, name_or_id: str) -> Optional[Dict]:
    cache = _CACHE_DIR / "species" / f"{name_or_id}.json"
    url = f"{POKEAPI_BASE}/pokemon-species/{name_or_id}"
    return await fetch_json(client, url, cache)


async def get_evolution_chain(client: httpx.AsyncClient, url: str) -> Optional[Dict]:
    # Extract chain ID from URL for caching
    chain_id = url.rstrip("/").split("/")[-1]
    cache = _CACHE_DIR / "evolution" / f"{chain_id}.json"
    return await fetch_json(client, url, cache)


def extract_evolution_ids(chain: Dict) -> List[int]:
    """Recursively extract all Pokemon IDs from an evolution chain."""
    ids = []

    def _traverse(node: Dict) -> None:
        species_url = node.get("species", {}).get("url", "")
        match = re.search(r"/pokemon-species/(\d+)/", species_url)
        if match:
            ids.append(int(match.group(1)))
        for evo in node.get("evolves_to", []):
            _traverse(evo)

    _traverse(chain.get("chain", {}))
    return ids


def get_english_category(species_data: Dict) -> str:
    """Extract English Pokédex category (e.g. 'Flame Pokémon')."""
    for entry in species_data.get("genera", []):
        if entry.get("language", {}).get("name") == "en":
            return entry["genus"]
    return "Unknown Pokémon"


def get_generation(species_data: Dict) -> int:
    gen_name = species_data.get("generation", {}).get("name", "generation-i")
    return GENERATION_MAP.get(gen_name, 1)


# --------------------------------------------------------------------------- #
# Bulbapedia Chinese name scraping
# --------------------------------------------------------------------------- #

async def get_chinese_name_from_bulbapedia(
    client: httpx.AsyncClient,
    english_name: str,
) -> Tuple[str, str]:
    """
    Scrape traditional and simplified Chinese names from Bulbapedia.
    Returns (traditional_zh, simplified_zh) or ("", "") on failure.
    """
    cache = _CACHE_DIR / "bulbapedia" / f"{english_name.lower()}.json"
    if cache.exists():
        with open(cache, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data.get("traditional", ""), data.get("simplified", "")

    # Bulbapedia URL uses underscores for spaces
    page_name = english_name.replace(" ", "_")
    url = f"{BULBAPEDIA_BASE}/{page_name}_(Pok%C3%A9mon)"

    try:
        await asyncio.sleep(REQUEST_DELAY)
        resp = await client.get(url, timeout=20.0, follow_redirects=True)
        if resp.status_code != 200:
            return "", ""

        soup = BeautifulSoup(resp.text, "lxml")

        traditional = ""
        simplified = ""

        # Look for Chinese name in the infobox table
        # Bulbapedia typically has a table with language names
        # The Chinese name section usually has 漢字 / 中文 labels

        # Strategy 1: Find "Chinese" label in name tables
        for td in soup.find_all("td"):
            text = td.get_text(strip=True)
            # Traditional Chinese (Taiwan) is usually listed as 繁體中文 or just Chinese
            if "中文" in text or "漢字" in text or "Chinese" in text:
                # Get sibling or next td
                next_td = td.find_next_sibling("td")
                if next_td:
                    zh = next_td.get_text(strip=True)
                    if zh and _is_chinese(zh):
                        traditional = zh
                        break

        # Strategy 2: Look in the infobox for zh name entries
        if not traditional:
            # Find all spans/divs that might contain Chinese characters
            for tag in soup.find_all(["span", "td", "th"]):
                text = tag.get_text(strip=True)
                if _is_chinese(text) and 2 <= len(text) <= 8:
                    # Plausible Pokemon name length in Chinese
                    traditional = text
                    break

        # For simplified: most names differ only slightly; use traditional as fallback
        # In practice, Bulbapedia often lists both
        if traditional and not simplified:
            simplified = _traditional_to_simplified_heuristic(traditional)

        result = {"traditional": traditional, "simplified": simplified}
        cache.parent.mkdir(parents=True, exist_ok=True)
        with open(cache, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False)

        return traditional, simplified

    except Exception as e:
        log.debug(f"Bulbapedia fetch failed for {english_name}: {e}")
        return "", ""


def _is_chinese(text: str) -> bool:
    """Check if text contains predominantly CJK characters."""
    if not text:
        return False
    cjk_count = sum(1 for c in text if "\u4e00" <= c <= "\u9fff")
    return cjk_count / len(text) > 0.5


def _traditional_to_simplified_heuristic(traditional: str) -> str:
    """
    Very basic traditional→simplified substitution for common Pokemon name characters.
    For production, use opencc or a full conversion table.
    """
    TRAD_TO_SIMP = {
        "龍": "龙", "獸": "兽", "龜": "龟", "夢": "梦", "幻": "幻",
        "飛": "飞", "電": "电", "蟲": "虫", "鳥": "鸟", "魚": "鱼",
        "貓": "猫", "狗": "狗", "馬": "马", "鳳": "凤", "鶴": "鹤",
        "鬥": "斗", "發": "发", "愛": "爱", "來": "来", "風": "风",
        "陽": "阳", "時": "时", "國": "国", "進": "进", "種": "种",
        "輝": "辉", "遊": "游", "傑": "杰", "聲": "声", "護": "护",
        "鐵": "铁", "會": "会", "樹": "树", "聯": "联", "實": "实",
        "裂": "裂", "螢": "萤", "燈": "灯", "雷": "雷", "閃": "闪",
    }
    result = []
    for char in traditional:
        result.append(TRAD_TO_SIMP.get(char, char))
    return "".join(result)


# --------------------------------------------------------------------------- #
# Main scraping logic
# --------------------------------------------------------------------------- #

async def scrape_single_pokemon(
    client: httpx.AsyncClient,
    name: str,
    use_bulbapedia: bool = True,
) -> Optional[Dict[str, Any]]:
    """Scrape all data for a single Pokemon. Returns None on critical failure."""
    # Fetch base Pokemon data
    poke_data = await get_pokemon_data(client, name)
    if poke_data is None:
        log.error(f"Failed to fetch base data for {name}")
        return None

    pokemon_id = poke_data["id"]
    english_name = next(
        (e["name"] for e in poke_data.get("names", []) if e.get("language", {}).get("name") == "en"),
        poke_data.get("name", name).title(),
    )
    # PokéAPI base endpoint gives 'name' not 'names'; species endpoint has names
    if not english_name:
        english_name = poke_data.get("name", name).replace("-", " ").title()
    else:
        english_name = poke_data.get("name", name).replace("-", " ").title()

    # Fetch species data (generation, category, evo chain URL)
    species_data = await get_pokemon_species(client, str(pokemon_id))
    if species_data is None:
        log.warning(f"[{english_name}] No species data, using placeholders")
        species_data = {}

    generation = get_generation(species_data)
    category = get_english_category(species_data)

    # Types
    types = [t["type"]["name"].capitalize() for t in poke_data.get("types", [])]
    type1 = types[0] if types else "Normal"
    type2 = types[1] if len(types) > 1 else None

    # Evolution line
    evo_ids = [pokemon_id]
    evo_url = species_data.get("evolution_chain", {}).get("url")
    if evo_url:
        evo_chain = await get_evolution_chain(client, evo_url)
        if evo_chain:
            evo_ids = extract_evolution_ids(evo_chain)

    # Sprite
    sprites = poke_data.get("sprites", {})
    sprite_url = (
        sprites.get("front_default")
        or sprites.get("other", {}).get("official-artwork", {}).get("front_default")
        or f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/{pokemon_id}.png"
    )

    # Chinese name
    name_zh = ""
    name_zh_simplified = ""

    if use_bulbapedia:
        # Use English name as it appears in the game (properly capitalized)
        en_name_for_bulba = english_name
        name_zh, name_zh_simplified = await get_chinese_name_from_bulbapedia(
            client, en_name_for_bulba
        )

    # Also try Chinese name from species data (if available)
    if not name_zh:
        for name_entry in species_data.get("names", []):
            lang = name_entry.get("language", {}).get("name", "")
            if lang == "zh-Hant":
                name_zh = name_entry["name"]
            elif lang == "zh-Hans":
                name_zh_simplified = name_entry["name"]

    if not name_zh:
        log.warning(f"[{english_name}] No Chinese name found, using placeholder")
        name_zh = english_name  # Fallback to English
        name_zh_simplified = english_name

    if not name_zh_simplified:
        name_zh_simplified = _traditional_to_simplified_heuristic(name_zh)

    # Pinyin
    pinyin_tones = get_pinyin_tones(name_zh)
    pinyin_numbered = get_pinyin_numbered(name_zh)
    ipa = get_ipa(pinyin_numbered)

    # Etymology
    etymology = get_etymology(name_zh)

    return {
        "id": pokemon_id,
        "name_en": english_name,
        "name_zh": name_zh,
        "name_zh_simplified": name_zh_simplified,
        "pinyin": pinyin_tones,
        "pinyin_numbered": pinyin_numbered,
        "ipa": ipa,
        "etymology": etymology,
        "generation": generation,
        "type1": type1,
        "type2": type2,
        "category": category,
        "evolution_line": evo_ids,
        "sprite_url": sprite_url or "",
        "audio_filename": None,
    }


async def run_scraper(limit: int = 1025, resume: bool = True, use_bulbapedia: bool = True) -> None:
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    (_CACHE_DIR / "pokemon").mkdir(exist_ok=True)
    (_CACHE_DIR / "species").mkdir(exist_ok=True)
    (_CACHE_DIR / "evolution").mkdir(exist_ok=True)
    (_CACHE_DIR / "bulbapedia").mkdir(exist_ok=True)

    # Load existing results if resuming
    existing_results: Dict[int, Dict] = {}
    if resume and _OUTPUT_JSON.exists():
        with open(_OUTPUT_JSON, "r", encoding="utf-8") as f:
            existing_list = json.load(f)
            existing_results = {p["id"]: p for p in existing_list}
        log.info(f"[resume] Loaded {len(existing_results)} existing Pokemon from {_OUTPUT_JSON}")

    headers = {
        "User-Agent": "Pokenese-Scraper/1.0 (educational project; contact via GitHub)",
    }

    async with httpx.AsyncClient(headers=headers) as client:
        # Get full Pokemon list
        log.info("[fetch] Getting Pokemon list from PokéAPI...")
        pokemon_list = await get_all_pokemon_list(client, limit=limit)
        log.info(f"[fetch] Found {len(pokemon_list)} Pokemon to process")

        results: List[Dict] = []
        failed: List[str] = []

        for i, poke_ref in enumerate(pokemon_list):
            poke_name = poke_ref["name"]

            # Extract ID from URL for quick lookup
            url_parts = poke_ref["url"].rstrip("/").split("/")
            try:
                poke_id = int(url_parts[-1])
            except ValueError:
                poke_id = -1

            # Skip if already scraped (resume mode)
            if resume and poke_id in existing_results:
                results.append(existing_results[poke_id])
                continue

            log.info(f"[{i+1}/{len(pokemon_list)}] Scraping {poke_name} (ID: {poke_id})...")

            try:
                data = await scrape_single_pokemon(client, poke_name, use_bulbapedia)
                if data:
                    results.append(data)
                    log.info(f"  ✓ {data['name_en']} | zh: {data['name_zh']} | {data['type1']}")
                else:
                    failed.append(poke_name)
                    log.error(f"  ✗ Failed: {poke_name}")
            except Exception as e:
                failed.append(poke_name)
                log.error(f"  ✗ Exception for {poke_name}: {e}")

            # Save progress every 50 Pokemon
            if len(results) % 50 == 0 and results:
                _write_json(results)
                log.info(f"[checkpoint] Saved {len(results)} Pokemon to {_OUTPUT_JSON}")

    # Sort by ID
    results.sort(key=lambda x: x["id"])

    # Final write
    _write_json(results)
    _write_typescript(results)

    log.info(f"\n[done] Scraped {len(results)} Pokemon")
    if failed:
        log.warning(f"[done] Failed for {len(failed)} Pokemon: {', '.join(failed[:20])}")
    log.info(f"[done] JSON → {_OUTPUT_JSON}")
    log.info(f"[done] TypeScript → {_OUTPUT_TS}")


def _write_json(results: List[Dict]) -> None:
    _OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with open(_OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)


def _write_typescript(results: List[Dict]) -> None:
    """Write results as a TypeScript constant file."""
    _OUTPUT_TS.parent.mkdir(parents=True, exist_ok=True)

    ts_lines = [
        "// Generated by scripts/scrape_pokemon.py",
        "// Do not edit directly — regenerate with: python backend/scripts/scrape_pokemon.py",
        "",
        'import type { PokemonType } from "@/types/pokemon";',
        "",
        "export const POKEMON_DATA: PokemonType[] = ",
    ]

    # Serialize to JSON then embed as TS value
    json_str = json.dumps(results, ensure_ascii=False, indent=2)
    ts_lines.append(json_str + ";")

    with open(_OUTPUT_TS, "w", encoding="utf-8") as f:
        f.write("\n".join(ts_lines) + "\n")


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #

def main() -> None:
    parser = argparse.ArgumentParser(description="Scrape Pokemon data")
    parser.add_argument("--limit", type=int, default=1025, help="Max Pokemon to scrape")
    parser.add_argument(
        "--no-resume", action="store_true", help="Re-scrape everything (ignore cache)"
    )
    parser.add_argument(
        "--no-bulbapedia", action="store_true", help="Skip Bulbapedia scraping"
    )
    args = parser.parse_args()

    asyncio.run(
        run_scraper(
            limit=args.limit,
            resume=not args.no_resume,
            use_bulbapedia=not args.no_bulbapedia,
        )
    )


if __name__ == "__main__":
    main()
