"""
Pokemon data loader.

Loads Pokemon data from data/pokemon.json (generated by scripts/scrape_pokemon.py).
Falls back to data/pokemon_sample.json if the full file is unavailable.
"""
from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

# Resolve the data directory relative to this file's location
_BASE_DIR = Path(__file__).resolve().parent.parent
_DATA_DIR = _BASE_DIR / "data"

_FULL_JSON = _DATA_DIR / "pokemon.json"
_SAMPLE_JSON = _DATA_DIR / "pokemon_sample.json"


@lru_cache(maxsize=1)
def load_pokemon_data() -> List[Dict[str, Any]]:
    """Return the full list of Pokemon dicts, loaded from JSON."""
    path = _FULL_JSON if _FULL_JSON.exists() else _SAMPLE_JSON
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data


@lru_cache(maxsize=1)
def get_pokemon_map() -> Dict[int, Dict[str, Any]]:
    """Return a mapping from pokemon_id -> pokemon dict."""
    return {p["id"]: p for p in load_pokemon_data()}


@lru_cache(maxsize=1)
def get_all_pokemon_ids() -> List[int]:
    """Return sorted list of all available Pokemon IDs."""
    return sorted(get_pokemon_map().keys())


def get_pokemon_by_id(pokemon_id: int) -> Optional[Dict[str, Any]]:
    return get_pokemon_map().get(pokemon_id)


def get_pokemon_by_name(name_en: str) -> Optional[Dict[str, Any]]:
    name_lower = name_en.strip().lower()
    for p in load_pokemon_data():
        if p["name_en"].lower() == name_lower:
            return p
    return None


def reload_pokemon_data() -> None:
    """Clear caches so data is reloaded on next access (useful after scraping)."""
    load_pokemon_data.cache_clear()
    get_pokemon_map.cache_clear()
    get_all_pokemon_ids.cache_clear()
